# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('isp', models.CharField(max_length=100)),
                ('points', models.IntegerField(max_length=3)),
                ('math_p', models.IntegerField(max_length=3)),
                ('inf_p', models.IntegerField(max_length=3)),
                ('rus_p', models.IntegerField(max_length=3)),
                ('dost_p', models.IntegerField(max_length=3)),
                ('docs', models.CharField(max_length=100)),
            ],
        ),
    ]
