# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20160715_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('isp', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=100)),
                ('math_p', models.CharField(max_length=100)),
                ('inf_p', models.CharField(max_length=100)),
                ('rus_p', models.CharField(max_length=100)),
                ('dost_p', models.CharField(max_length=100)),
                ('docs', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-points']},
        ),
    ]
